### ISSUE TITLE
Problem with gradient of #> and/or headTail

### ISSUE THREAD

**Issue by gilgamec** [mstksg/hmatrix-backprop#1]
The simplest I've been able to get this problem down to is
``` haskell
simple :: Reifies z W => BVar z (R 1) -> BVar z Double
simple x = fst . headTail $ auto (konst 1 :: L 1 1) #> x
```
This compiles fine, but taking the `gradBP` of this at seemingly any point results in a _runtime_ dimension exception!
```
*** Exception: inconsistent dimensions in matrix product (1,1) x (2,1)
CallStack (from HasCallStack):
  error, called at src/Internal/LAPACK.hs:63:31 in hmatrix-0.20.0.0-2Bb8WzrefWrLcS7r5U0WKK:Internal.LAPACK
```
I couldn't get a crash without both the `headTail` and the matrix multiplication.

**Comment by mstksg** [comment]
Hm this is definitely a bug :)  Will try to narrow this down, thanks for bringing this to my attention!

**Comment by mstksg** [comment]
Seems to come from an *hmatrix* bug.  The reason the crash happens is because `headTail` concatenates the head and tail back together to compute the gradient.  In this case, the tail is a 0-length vector.  However, hmatrix internally represents a constant vector as a 1-length vector and converts it back to the "real" size when doing vector concatenation.  The bug comes from the fact that this back-conversion has a bug, and converts the zero-vector to a 1-item vector, and so and (1 :: R 1) # (6 :: R 0) = [1, 6] :: R 1.

So, this crash should happen every time you `headTail` a single-item vector that was created using matrix multiplication.

I submitted a PR to hmatrix (haskell-numerics/hmatrix#310) that should fix this :)

**Comment by mstksg** [comment]
Just as an update, this is now fixed in hmatrix as of https://github.com/haskell-numerics/hmatrix/commit/150f206a4e3ddbe71371634c12a7ea640940b0f1
